# Generated by Django 2.0.1 on 2018-03-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=300)),
            ],
        ),
    ]
