# Generated by Django 2.0.1 on 2018-03-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_name',
        ),
    ]
